In [1]:
np.std([1,2,3])



NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
# Statement to import the numpy library
import numpy as np

In [5]:
#one dimensional array of some prime numbers
prime_array = np.array([2,3,5,7,11])
print(prime_array)

[ 2  3  5  7 11]


In [6]:
type(prime_array)


numpy.ndarray

In [8]:
# 2d array 
another_array = np.array([[2,3],[7,8]])
print(another_array)

[[2 3]
 [7 8]]


In [9]:
# Create a three-dimensional array 
threeD_array = np.array([[[1,2],[3,4]],
                        [[5,6],[7,8]]])
print(threeD_array)
print(threeD_array.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


# Array inspection

# 1. ndarray.shape
this is a tuple consting of array dimensions and can be used to resize the array


In [11]:
alma_array = np.array([[1,2,3],[4,5,6]]) 
print(alma_array.shape)


(2, 3)


In [12]:
alma_array = np.array([[1,2,3,4],[4,5,9,10]]) 
print(alma_array.shape)

(2, 4)


In [13]:
alma_array = np.array([[[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]]) 
# print(alma_array)
print(alma_array.shape)

(4, 2, 3)


# 2. ndarray.ndim
thsi returns the no of array dimensions

In [14]:
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print("Dimensions of 'array_of_integers' = ", array_of_integers.ndim)
 
sample_2d_array = np.array([[1,2,3],[4,5,6]]) 
print("Dimensions of 'sample_2d_array' = ", sample_2d_array.ndim)

Dimensions of 'array_of_integers' =  1
Dimensions of 'sample_2d_array' =  2


# 3. ndarray.size
this returns the total number of elements of the array

In [15]:
# Print the size of array
array_of_integers = np.array([0,1,2,3,4,5,6,7,8,9])
print(f"The total number of elements in our array 'array_of_integers' =  {array_of_integers.size}")
 
sample_2d_array = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in our array 'sample_2d_array' =  {sample_2d_array.size}")

The total number of elements in our array 'array_of_integers' =  10
The total number of elements in our array 'sample_2d_array' =  6


# 4. ndarray.dtype
this returns the data type of the array

In [16]:
my_array = np.array([1,2,3,4,5])
print(my_array.dtype)

int32


In [17]:
# Print the dtype of another array
my_array = np.array([1,2.0,3,4,5,'abc'])
print(my_array.dtype)

<U32


In [18]:
my_array = np.array(['abd','bcd','abc'])
print(my_array.dtype)

<U3


# 5. ndarray.astype
this changes the datatype of an array


In [19]:
# Create an array
arravali = np.array([2,3,4])
print(arravali)
print(arravali.dtype)
 
# Change the datatype of the array to float
arravali_ = arravali.astype('float64')
print(arravali_)
print(arravali_.dtype)

[2 3 4]
int32
[2. 3. 4.]
float64


In [20]:
import numpy as np 
import sys     #This module provides access to some vaiables used or maintained by 
               #the interpreter and to functions that interact strongly with the interpretar
  
# declaring a list of 10 elements  
S = [0,1,2,3,4,5,6,7,8,9]  
print("Size of each element of list in bytes: ",sys.getsizeof(S)) 
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S)) 
  
# declaring a Numpy array of 10 elements  
D= np.array([0,1,2,3,4,5,6,7,8,9] ) 
print("Size of each element of the Numpy array in bytes: ",D.itemsize) 
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  152
Size of the whole list in bytes:  1520
Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  40


In [21]:
import numpy as np
import time 
   
# size of arrays and lists 
size = 100000 
   
# declaring lists 
list1 = range(size) 
list2 = range(size) 
   
# declaring arrays 
array1 = np.arange(size)   
array2 = np.arange(size) 
   
# capturing time before the multiplication of Python lists 
initialTime = time.time() 
  
# multiplying  elements of both the lists and stored in another list 
resultantList = [(a * b) for a, b in zip(list1, list2)] 
   
# calculating execution time 
print("Time taken by Lists to perform multiplication:",  
      (time.time() - initialTime), 
      "seconds") 
   
# capturing time before the multiplication of Numpy arrays 
initialTime = time.time() 
  
# multiplying  elements of both the Numpy arrays and stored in another Numpy array  
resultantArray = array1 * array2 
   
# calculating execution time  
print("Time taken by NumPy Arrays to perform multiplication:", 
      (time.time() - initialTime), 
      "seconds")

Time taken by Lists to perform multiplication: 0.008084535598754883 seconds
Time taken by NumPy Arrays to perform multiplication: 0.0010023117065429688 seconds


# functionality

In [22]:
import numpy as np 
  
# declaring a list 
ls =[1, 2, 3] 
  
# converting the list into a Numpy array 
arr = np.array(ls) 
  
try: 
    # adding 4 to each element of list 
    ls = ls + 4
      
except(TypeError): 
    print("Lists don't support list + int") 
  
# now on array 
try: 
    # adding 4 to each element of Numpy array 
    arr = arr + 4
  
    # printing the Numpy array 
    print("Modified Numpy array: ",arr) 
      
except(TypeError): 
    print("Numpy arrays don't support list + int")

Lists don't support list + int
Modified Numpy array:  [5 6 7]


# different ways of creating nd array
unitialized

In [23]:
# Creating an uninitialized array of a specified shape
uninitialized_array = np.empty([5,3],dtype=int)
print(uninitialized_array)

[[4128860 6029375 3801155]
 [5570652 6619251 7536754]
 [4718684 6029392 7340097]
 [4456560 7602273 6029409]
 [7274572 6357091     108]]


# initialized with zeros

In [24]:
# Intializing the array with zeros
zeros_array = np.zeros((3,3)) # Default dtype = float
another_zeros_array = np.zeros((4,3) , dtype=int)
print(zeros_array)
print(another_zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [26]:
ones_array = np.ones((3,3)) # Default dtype = float
another_ones_array = np.ones((2,3) , dtype=int)
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
bunch_of_ones = np.ones((4,3))
bunch_of_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# Trying to change the shape of our array
bunch_of_ones.shape = (2,6)
bunch_of_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Array from numerical ranges

In [29]:
array_with_range = np.arange(5)
array_with_range

array([0, 1, 2, 3, 4])

In [30]:
another_array_with_range = np.arange(10,20,2) 
another_array_with_range

array([10, 12, 14, 16, 18])

In [31]:
# to get the number of evenly spaced values between intervals
# Parameters for the function - np.linespace(start, stop, num, endpoint, retstep, dtype)
# dtype is that of output array
linearly_spaced_values = np.linspace(10,20,9 , endpoint = False, retstep = True) 
linearly_spaced_values

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889]),
 1.1111111111111112)

# Array from random numbers

In [32]:
random_array = np.random.random((4,3))
print(random_array)

[[0.26210034 0.86923986 0.13792793]
 [0.25710404 0.35975864 0.70605564]
 [0.97928956 0.61947314 0.7434417 ]
 [0.52462689 0.45126149 0.54954417]]


In [33]:
random_integral_array = np.random.randint(0,5,size=(2,3,4))
print(random_integral_array)

[[[4 4 4 2]
  [4 1 1 3]
  [4 4 3 1]]

 [[2 3 0 3]
  [4 2 2 1]
  [4 3 3 4]]]


In [34]:
a = np.full((3,3),30)
print(a)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [35]:
a = np.ones((3,3))*30
print(a)

[[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]


In [36]:
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# creating nd array with existing data

In [37]:
# convert tuple to ndarray
typical_tuple = (1,2,3) 
corresponding_array = np.asarray(typical_tuple) 
corresponding_array

array([1, 2, 3])

In [38]:
a = np.arange(10) 
a[5]

5

In [39]:
a = np.arange(10) 
a[2:5]

array([2, 3, 4])

In [40]:
# slice items between indexes in steps
a = np.random.random(10) 
a

array([0.90715898, 0.52833274, 0.19955769, 0.82292364, 0.13551943,
       0.92618109, 0.66867115, 0.70355647, 0.99706073, 0.44958962])

In [41]:
a[::2]\

SyntaxError: unexpected EOF while parsing (2946733185.py, line 1)

In [42]:
a = np.arange(10)
print(a[:6:2]) # starting index is unspecified (default = 0)
print(a[1::2]) # ending index is unspecified (default = array size)
print(a[1:6:]) # steps is unspecified (default = 1)

[0 2 4]
[1 3 5 7 9]
[1 2 3 4 5]


In [43]:
# retrieving elements from a 2-D array
a = np.array([[1,2,3],[4,5,6]])
print(a[1,2])
# print(a[1,2])

6


In [44]:
# getting the entire array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0:2]) 
print(a[0:2,-2:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [45]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:1,:])

[[1 2 3]]


In [46]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:1,1:2])

[[2]]


In [47]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[:,0:1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [7]]


In [48]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[::2,0:1])

[[1]
 [7]]


In [49]:
# Create a 2 D Array
arravali = np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f" \n The shape of the array is {arravali.shape}")

The defined array is 
[[44 21]
 [10 42]
 [44 17]
 [35 10]
 [13 33]
 [23 36]
 [40 31]
 [30 40]]
 
 The shape of the array is (8, 2)


In [50]:
nilgiri =np.transpose(arravali)
print(f" The transpose of the array is \n{nilgiri}")
print(f" \n The shape of the array is {nilgiri.shape}")

 The transpose of the array is 
[[44 10 44 35 13 23 40 30]
 [21 42 17 10 33 36 31 40]]
 
 The shape of the array is (2, 8)


In [51]:
# 3D Array
random_3d_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")
print(f" \n The shape of the array is {random_3d_array.shape}")

The defined array is 
[[[28 17 22 11]
  [38 18 38 19]]

 [[33 44 30 22]
  [13 44 28 20]]

 [[24 38 17 39]
  [13 37 11 21]]]
 
 The shape of the array is (3, 2, 4)


In [52]:
# Storing the transpose of the created 3d array
transposed_3d_array =np.transpose(random_3d_array)
print(f" The transpose of the array is \n{transposed_3d_array}")
print(f" \n The shape of the array is {transposed_3d_array.shape}")

 The transpose of the array is 
[[[28 33 24]
  [38 13 13]]

 [[17 44 38]
  [18 44 37]]

 [[22 30 17]
  [38 28 11]]

 [[11 22 39]
  [19 20 21]]]
 
 The shape of the array is (4, 2, 3)


In [53]:
random_cohort = np.array(np.random.randint(10,45,(3,8))) # 2D
print(f"The defined array is \n{random_cohort}")
print(f" \n The shape of the array is {random_cohort.shape}")

The defined array is 
[[26 41 40 19 15 23 33 40]
 [30 26 37 10 20 30 23 33]
 [12 14 32 30 38 38 41 39]]
 
 The shape of the array is (3, 8)


In [54]:
# Now we can reshape this to 1-D,2-D or 3-D array
new_shape = (2,4,3)
reshaped_random_cohort = np.reshape(random_cohort,new_shape)
print(f"The reshaped array is \n{reshaped_random_cohort}")
print(f" \n The shape of the array is {reshaped_random_cohort.shape}")

The reshaped array is 
[[[26 41 40]
  [19 15 23]
  [33 40 30]
  [26 37 10]]

 [[20 30 23]
  [33 12 14]
  [32 30 38]
  [38 41 39]]]
 
 The shape of the array is (2, 4, 3)


In [55]:
# Create a three-dimensional array
random_3D_cohort = np.array(np.random.randint(10,45,(3,6,2))) 
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[42 32]
  [28 16]
  [13 12]
  [35 29]
  [12 21]
  [12 25]]

 [[16 13]
  [38 20]
  [38 24]
  [28 37]
  [41 26]
  [11 26]]

 [[13 24]
  [20 38]
  [23 28]
  [19 21]
  [43 16]
  [10 15]]]
 
 The shape of the array is (3, 6, 2)


In [56]:
# Intialize a 3D array
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6))) 
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[36 38 17 42 44 22]
  [40 23 40 20 29 37]
  [17 29 41 21 25 43]
  [14 23 13 27 43 20]]

 [[13 36 40 23 21 19]
  [35 24 42 43 44 36]
  [26 30 30 32 25 35]
  [42 12 15 25 25 41]]]
 
 The shape of the array is (2, 4, 6)


In [57]:
# Resize the created 3D array
new_shape = (4,3,6)
resized_random_3D_cohort = np.resize(random_3D_cohort,new_shape)
print(f"The resized array is \n{resized_random_3D_cohort}")
print(f" \n The shape of the array is {resized_random_3D_cohort.shape}")

The resized array is 
[[[36 38 17 42 44 22]
  [40 23 40 20 29 37]
  [17 29 41 21 25 43]]

 [[14 23 13 27 43 20]
  [13 36 40 23 21 19]
  [35 24 42 43 44 36]]

 [[26 30 30 32 25 35]
  [42 12 15 25 25 41]
  [36 38 17 42 44 22]]

 [[40 23 40 20 29 37]
  [17 29 41 21 25 43]
  [14 23 13 27 43 20]]]
 
 The shape of the array is (4, 3, 6)


In [58]:
# Intialize a 3D array
random_3D_cohort = np.array(np.random.randint(10,45,(2,4,6))) 
print(f"The defined array is \n{random_3D_cohort}")
print(f" \n The shape of the array is {random_3D_cohort.shape}")

The defined array is 
[[[31 21 39 43 37 19]
  [42 36 30 41 31 37]
  [36 26 32 38 15 35]
  [10 33 40 30 33 15]]

 [[30 23 22 30 26 21]
  [15 34 30 17 29 42]
  [12 43 35 25 24 23]
  [33 26 22 25 42 43]]]
 
 The shape of the array is (2, 4, 6)


In [59]:
# Flatten the 3D array
random_3D_cohort.flatten()

array([31, 21, 39, 43, 37, 19, 42, 36, 30, 41, 31, 37, 36, 26, 32, 38, 15,
       35, 10, 33, 40, 30, 33, 15, 30, 23, 22, 30, 26, 21, 15, 34, 30, 17,
       29, 42, 12, 43, 35, 25, 24, 23, 33, 26, 22, 25, 42, 43])

In [60]:
# Flattens the array in row-major order with 'C'
random_3D_cohort.flatten(order='F')

array([31, 30, 42, 15, 36, 12, 10, 33, 21, 23, 36, 34, 26, 43, 33, 26, 39,
       22, 30, 30, 32, 35, 40, 22, 43, 30, 41, 17, 38, 25, 30, 25, 37, 26,
       31, 29, 15, 24, 33, 42, 19, 21, 37, 42, 35, 23, 15, 43])